### ISSUE TITLE
Typo in ibm_csm_session_action example

### ISSUE THREAD

**Issue by dblea0** [ansible-collections/ibm.csm#24]
##### SUMMARY

The example set in the ibm_csm_session_action file is showing as an ibm_csm_active_standby_action

##### ISSUE TYPE
- Typo Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```

**Comment by blearandy** [comment]
Fixed in https://github.com/ansible-collections/ibm.csm/pull/26
